import matter from "gray-matter";
import type { Root } from "hast";
import remarkGfm from "remark-gfm";
import remarkParse from "remark-parse";
import remarkRehype from "remark-rehype";
import { unified } from "unified";

/**
 * One entry on the References page, generated from a note in the vault's
 * `Sources` folder.
 */
export interface Source {
  /**
   * The vault filename without `.md`, e.g. `"caplin-1998"`. Notes cite the source
   * as `[[Sources/<shortForm>]]`, and the page uses it as the row's anchor id.
   */
  shortForm: string;
  /** The note's citation text, rendered to hast. */
  citation: Root;
}

const WIKILINK_LINE_RE = /^\s*!?\[\[[^\]]*\]\]\s*$/;

const processor = unified().use(remarkParse).use(remarkGfm).use(remarkRehype);

/**
 * Parse a `Sources/…` note into a {@link Source}. Lines holding only a wikilink,
 * such as the `[[Sources/Bibliography]]` backlink, are dropped.
 *
 * @param fileName - The note's filename, including `.md`.
 * @param raw - The note's full markdown source.
 * @returns The source, or null when the note has no citation text.
 */
export function parseSource(fileName: string, raw: string): Source | null {
  const body = matter(raw)
    .content.split("\n")
    .filter((line) => !WIKILINK_LINE_RE.test(line))
    .join("\n")
    .trim();
  if (body === "") return null;
  const tree = processor.runSync(processor.parse(body));
  const citation = JSON.parse(
    JSON.stringify(tree, (key, value) => (key === "position" ? undefined : value)),
  ) as Root;
  return { shortForm: fileName.replace(/\.md$/, ""), citation };
}

/**
 * Render the source of `references.gen.ts`, which exports `SOURCES` sorted by
 * short form.
 *
 * @param sources - The parsed sources, in any order.
 * @returns The module text. Equal inputs MUST yield identical text.
 */
export function renderSourcesModule(sources: Source[]): string {
  const sorted = [...sources].sort((a, b) =>
    a.shortForm < b.shortForm ? -1 : a.shortForm > b.shortForm ? 1 : 0,
  );
  return (
    "// Generated by `pnpm references` from the vault's Sources folder. Do not edit.\n\n" +
    'import type { Source } from "./references.ts";\n\n' +
    "export const SOURCES: Source[] = [\n" +
    sorted.map((source) => `  ${JSON.stringify(source)},\n`).join("") +
    "];\n"
  );
}
